In [81]:
## Standard Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
## Importing the OS and JSON Modules
import os,json

In [82]:
# Load the data from CSV files
superhero_info = pd.read_csv('superhero_info - superhero_info.csv')
superhero_powers = pd.read_csv('superhero_powers - superhero_powers.csv')

In [83]:
superhero_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Hero|Publisher  463 non-null    object
 1   Gender          463 non-null    object
 2   Race            463 non-null    object
 3   Alignment       463 non-null    object
 4   Hair color      463 non-null    object
 5   Eye color       463 non-null    object
 6   Skin color      463 non-null    object
 7   Measurements    463 non-null    object
dtypes: object(8)
memory usage: 29.1+ KB

In [84]:
superhero_info.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"

In [85]:
superhero_powers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hero_names  667 non-null    object
 1   Powers      667 non-null    object
dtypes: object(2)
memory usage: 10.5+ KB

In [86]:
superhero_powers.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [87]:
# Merge the two dataframes on 'Hero' column
df = pd.concat((superhero_powers, superhero_info), axis = 1)
df

,hero_names,Powers,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abe Sapien,"Agility,Accelerated Healing,Cold Resistance,Du...",Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abin Sur,Lantern Power Ring,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Abomination,"Accelerated Healing,Intelligence,Super Strengt...",Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"
...,...,...,...,...,...,...,...,...,...,...
662,Yellowjacket II,"Flight,Energy Blasts,Size Changing",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
663,Ymir,"Cold Resistance,Durability,Longevity,Super Str...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
664,Yoda,"Agility,Stealth,Danger Sense,Marksmanship,Weap...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
665,Zatanna,"Cryokinesis,Telepathy,Magic,Fire Control,Proba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,Zoom,"Super Speed,Intangibility,Time Travel,Time Man...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
df['Hero|Publisher'].str.split('|',expand=True)

                 0                  1
0           A-Bomb      Marvel Comics
1       Abe Sapien  Dark Horse Comics
2         Abin Sur          DC Comics
3      Abomination      Marvel Comics
4    Absorbing Man      Marvel Comics
..             ...                ...
662            NaN                NaN
663            NaN                NaN
664            NaN                NaN
665            NaN                NaN
666            NaN                NaN

[667 rows x 2 columns]

In [89]:
df[['Hero','Publisher']] = df['Hero|Publisher'].str.split('|',expand=True)
df.head(2)

,hero_names,Powers,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics

In [90]:
## drop the original column 
df = df.drop(columns=['Hero|Publisher', 'Hero'])
df.head(2)

,hero_names,Powers,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Publisher
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Marvel Comics
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Dark Horse Comics

In [103]:
df.rename(columns={'hero_names': 'Hero'}, inplace=True)
df.head(2)

,Hero,Gender,Race,Alignment,Hair color,Eye color,Skin color,Publisher,Height(cm),Weight(kg),...,Vision - Thermal,Vision - X-Ray,Vitakinesis,Wallcrawling,Water Control,Weapon-based Powers,Weapons Master,Weather Control,Web Creation,Wind Control
0,3-D Man,Male,Human,good,No Hair,yellow,Unknown,Marvel Comics,203.0,441.0,...,0,0,0,0,0,0,0,0,0,0
1,A-Bomb,Male,Icthyo Sapien,good,No Hair,blue,blue,Dark Horse Comics,191.0,65.0,...,0,0,0,0,0,0,0,0,0,0

In [91]:
df['Measurements'].str.split(',',expand=True)

                         0                       1
0    {'Height': '203.0 cm'   'Weight': '441.0 kg'}
1    {'Height': '191.0 cm'    'Weight': '65.0 kg'}
2    {'Height': '185.0 cm'    'Weight': '90.0 kg'}
3    {'Height': '203.0 cm'   'Weight': '441.0 kg'}
4    {'Height': '193.0 cm'   'Weight': '122.0 kg'}
..                     ...                     ...
662                    NaN                     NaN
663                    NaN                     NaN
664                    NaN                     NaN
665                    NaN                     NaN
666                    NaN                     NaN

[667 rows x 2 columns]

In [92]:
df[['Height(cm)','Weight(kg)']] = df['Measurements'].str.split(',',expand=True)
df.head(2)

,hero_names,Powers,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Publisher,Height(cm),Weight(kg)
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Marvel Comics,{'Height': '203.0 cm','Weight': '441.0 kg'}
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Dark Horse Comics,{'Height': '191.0 cm','Weight': '65.0 kg'}

In [93]:
## drop the original column 
df = df.drop(columns=['Measurements'])
df.head(2)

,hero_names,Powers,Gender,Race,Alignment,Hair color,Eye color,Skin color,Publisher,Height(cm),Weight(kg)
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed",Male,Human,good,No Hair,yellow,Unknown,Marvel Comics,{'Height': '203.0 cm','Weight': '441.0 kg'}
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Male,Icthyo Sapien,good,No Hair,blue,blue,Dark Horse Comics,{'Height': '191.0 cm','Weight': '65.0 kg'}

In [94]:
to_replace = ['{','}',"'Height': ","'",' cm']

for char in to_replace:
    df['Height(cm)'] = df['Height(cm)'].str.replace(char,'',regex=False)
    
df['Height(cm)'].head()

0    203.0
1    191.0
2    185.0
3    203.0
4    193.0
Name: Height(cm), dtype: object

In [95]:
to_replace = ['{','}',"'Weight': ","'",' kg']

for char in to_replace:
    df['Weight(kg)'] = df['Weight(kg)'].str.replace(char,'',regex=False)
    
df['Weight(kg)'].head()

0     441.0
1      65.0
2      90.0
3     441.0
4     122.0
Name: Weight(kg), dtype: object

In [96]:
df['Weight(kg)'] = pd.to_numeric(df['Weight(kg)'], errors='coerce')
df['Weight(kg)'].head()

0    441.0
1     65.0
2     90.0
3    441.0
4    122.0
Name: Weight(kg), dtype: float64

In [97]:
df['Height(cm)'] = pd.to_numeric(df['Height(cm)'], errors='coerce')
df['Height(cm)'].head()

0    203.0
1    191.0
2    185.0
3    203.0
4    193.0
Name: Height(cm), dtype: float64

In [98]:
df['Powers'].value_counts()

Intelligence                                                                                                                                                                                                                                                         8
Durability,Super Strength                                                                                                                                                                                                                                            5
Agility,Stealth,Marksmanship,Weapons Master,Stamina                                                                                                                                                                                                                  4
Marksmanship                                                                                                                                                                                                                                                         4
Teleportation                                                                                                                                                                                                                                                        4
                                                                                                                                                                                                                                                                    ..
Accelerated Healing,Flight,Telepathy,Energy Blasts,Teleportation,Telekinesis,Astral Projection,Psionic Powers,Mind Blast,Regeneration,Illusions,Resurrection                                                                                                         1
Flight,Telepathy,Animal Oriented Powers,Gliding                                                                                                                                                                                                                      1
Accelerated Healing,Durability,Energy Absorption,Flight,Super Strength,Telepathy,Energy Blasts,Size Changing,Super Speed,Darkforce Manipulation,Enhanced Senses,Phasing,Invulnerability,Self-Sustenance,Gravity Control,Energy Manipulation,Time Travel,Illusions    1
Agility,Accelerated Healing,Super Strength,Super Speed,Animal Oriented Powers,Enhanced Senses,Jump,Reflexes,Natural Weapons                                                                                                                                          1
Super Speed,Intangibility,Time Travel,Time Manipulation                                                                                                                                                                                                              1
Name: Powers, Length: 608, dtype: int64

In [99]:
# Split the 'Powers' column into separate columns for each power and one-hot encode them
powers_dummies = df['Powers'].str.get_dummies(sep=',')
powers_dummies

,Accelerated Healing,Adaptation,Agility,Animal Attributes,Animal Control,Animal Oriented Powers,Animation,Anti-Gravity,Astral Projection,Astral Travel,...,Vision - Thermal,Vision - X-Ray,Vitakinesis,Wallcrawling,Water Control,Weapon-based Powers,Weapons Master,Weather Control,Web Creation,Wind Control
0,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
663,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
664,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
665,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
666,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [100]:
# Concatenate the one-hot encoded powers with the original DataFrame
df = pd.concat([df, powers_dummies], axis=1)

In [101]:
df.drop(columns=['Powers'], inplace=True)
df

,hero_names,Gender,Race,Alignment,Hair color,Eye color,Skin color,Publisher,Height(cm),Weight(kg),...,Vision - Thermal,Vision - X-Ray,Vitakinesis,Wallcrawling,Water Control,Weapon-based Powers,Weapons Master,Weather Control,Web Creation,Wind Control
0,3-D Man,Male,Human,good,No Hair,yellow,Unknown,Marvel Comics,203.0,441.0,...,0,0,0,0,0,0,0,0,0,0
1,A-Bomb,Male,Icthyo Sapien,good,No Hair,blue,blue,Dark Horse Comics,191.0,65.0,...,0,0,0,0,0,0,0,0,0,0
2,Abe Sapien,Male,Ungaran,good,No Hair,blue,red,DC Comics,185.0,90.0,...,0,0,0,0,0,0,1,0,0,0
3,Abin Sur,Male,Human / Radiation,bad,No Hair,green,Unknown,Marvel Comics,203.0,441.0,...,0,0,0,0,0,0,0,0,0,0
4,Abomination,Male,Human,bad,No Hair,blue,Unknown,Marvel Comics,193.0,122.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662,Yellowjacket II,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
663,Ymir,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
664,Yoda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,1,0,0,0
665,Zatanna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,0,0,1,0,0
666,Zoom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

In [108]:
# Calculate the average weight of superheroes with Super Speed
average_weight_with_super_speed = df[df['Super Speed'] == 1]['Weight(kg)'].mean()

# Calculate the average weight of superheroes without Super Speed
average_weight_without_super_speed = df[df['Super Speed'] == 0]['Weight(kg)'].mean()

print("Average weight of superheroes with Super Speed in kg:", average_weight_with_super_speed)
print("Average weight of superheroes without Super Speed in kg:", average_weight_without_super_speed)

Average weight of superheroes with Super Speed in kg: 113.39181286549707
Average weight of superheroes without Super Speed in kg: 113.70547945205479

In [109]:
# Calculate average height of heroes for each publisher
average_height_by_publisher = df.groupby('Publisher')['Height(cm)'].mean()

print("Average height of heroes by publisher in cm:")
print(average_height_by_publisher)

Average height of heroes by publisher in cm:
Publisher
DC Comics            181.923913
Dark Horse Comics    176.909091
George Lucas         159.600000
Image Comics         211.000000
Marvel Comics        191.546128
Shueisha             171.500000
Star Trek            181.500000
Team Epic TV         180.750000
Unknown              178.000000
Name: Height(cm), dtype: float64